# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/3.7"
    schedule:
      interval: "daily"
    target-branch: "main"
    ignore:
      - dependency-name: "python"
        update-types: [ "version-update:semver-major", "version-update:semver-minor" ]
  - package-ecosystem: "docker"
    directory: "/3.8"
    schedule:
      interval: "daily"
    target-branch: "main"
    ignore:
      - dependency-name: "python"
        update-types: [ "version-update:semver-major", "version-update:semver-minor" ]
  - package-ecosystem: "docker"
    directory: "/3.9"
    schedule:
      interval: "daily"
    target-branch: "main"
    ignore:
      - dependency-name: "python"
        update-types: [ "version-update:semver-major", "version-update:semver-minor" ]
  - package-ecosystem: "docker"
    directory: "/3.10"
    schedule:
      interval: "daily"
    target-branch: "main"
    ignore:
      - dependency-name: "python"
        update-types: [ "version-update:semver-major", "version-update:semver-minor" ]
  - package-ecosystem: "docker"
    directory: "/3.11"
    schedule:
      interval: "daily"
    target-branch: "main"
    ignore:
      - dependency-name: "python"
        update-types: [ "version-update:semver-major", "version-update:semver-minor" ]
  - package-ecosystem: "docker"
    directory: "/3.12"
    schedule:
      interval: "daily"
    target-branch: "main"
    ignore:
      - dependency-name: "python"
        update-types: [ "version-update:semver-major", "version-update:semver-minor" ]
